name: Pull Request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: node:12-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run linting
      run: npm test
    - name: Run backstop
      run: npm run backstop:ci
    